### ISSUE TITLE
not possible to build kernel 6.1

### ISSUE THREAD

**Issue by karu2003** [free-electrons/cedrus-frame-test#24]
not possible to build in kernel 6.1
pi@bpim2z:~/src/v4l2-request-test$ make
 CC     v4l2-request-test.c
In file included from v4l2-request-test.h:27,
                 from v4l2-request-test.c:38:
include/h264-ctrls.h:52:8: error: redefinition of ‘struct v4l2_ctrl_h264_sps’
   52 | struct v4l2_ctrl_h264_sps {
      |        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/linux/videodev2.h:65,
                 from v4l2-request-test.c:34:
.......
